Immobilier\ManagerBundle\Entity\Annonce:
    type: entity
    table: annonce
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 100
            nullable: true
        idRubrique:
            type: integer
            unsigned: false
            nullable: false
            column: id_rubrique
        idCategory:
            type: integer
            unsigned: false
            nullable: false
            column: id_category
        nature:
            type: integer
            unsigned: false
            nullable: false
            column: nature
        idType:
            type: integer
            unsigned: false
            nullable: false
            column: id_type
        surface:
            type: string
            length: 50
            fixed: false
            nullable: false
        prix:
            type: integer
            unsigned: false
            nullable: false
        description:
            type: text
            fixed: false
            nullable: true
        lng:
            type: string
            length: 20
            nullable: true
        lat:
            type: string
            length: 20
            nullable: true
        idPays:
            type: integer
            unsigned: false
            nullable: false
            column: id_pays
        idGouvernorat:
            type: integer
            unsigned: false
            nullable: false
            column: id_gouvernorat
        idDelegation:
            type: integer
            unsigned: false
            nullable: false
            column: id_delegation
        idLocalite:
            type: integer
            unsigned: false
            nullable: false
            column: id_localite
        idUser:
            type: integer
            unsigned: false
            nullable: false
            column: id_user
    lifecycleCallbacks: {  }
