Immobilier\ManagerBundle\Entity\Delegation:
    type: entity
    table: delegation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 200
            fixed: false
            nullable: false
        idGouvernorat:
            type: integer
            unsigned: false
            nullable: false
            column: id_gouvernorat
    manyToOne:
        gouvernorat:
            targetEntity: Gouvernorat
            inversedBy: delegations
            joinColumn:
                name: id_gouvernorat
                referencedColumnName: id
    oneToMany:
        localites:
            targetEntity: Localite
            mappedBy: delegation
    lifecycleCallbacks: {  }
