Immobilier\ManagerBundle\Entity\Gouvernorat:
    type: entity
    table: gouvernorat
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
        idPays:
            type: integer
            unsigned: false
            nullable: false
            column: id_pays
    manyToOne:
        pays:
            targetEntity: Pays
            inversedBy: gouvernorats
            joinColumn:
                name: id_pays
                referencedColumnName: id
    oneToMany:
        delegations:
            targetEntity: Delegation
            mappedBy: gouvernorat
    lifecycleCallbacks: {  }
