Immobilier\ManagerBundle\Entity\Localite:
    type: entity
    table: localite
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 200
            fixed: false
            nullable: false
        delegationId:
            type: integer
            unsigned: false
            nullable: false
            column: id_delegation
    lifecycleCallbacks: {  }
