Immobilier\ManagerBundle\Entity\Photo:
    type: entity
    table: photo
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
        path:
            type: string
            length: 255
            fixed: false
            nullable: true
        idAnnonce:
            type: integer
            unsigned: false
            nullable: true
            column: id_annonce
    lifecycleCallbacks: {  }
