Immobilier\ManagerBundle\Entity\Type:
    type: entity
    table: type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
