immobilier_manager_homepage:
    pattern:  /home
    defaults: { _controller: ImmobilierManagerBundle:Default:index }
######Photo root###########
immobilier_manager_createPhoto:
    pattern:  /create/photo/{namePhoto}
    defaults: { _controller: ImmobilierManagerBundle:Default:createPhoto }
######User root###########
immobilier_manager_createUser:
    pattern:  /create/user
    defaults: { _controller: ImmobilierManagerBundle:User:createUser }
immobilier_manager_createUserForm:
    pattern:  /create/user_form
    defaults: { _controller: ImmobilierManagerBundle:User:createUserForm }
immobilier_manager_createSynchroUser:
    pattern:  /create/synchro/user/{login}/{passwd}/{email}
    defaults: { _controller: ImmobilierManagerBundle:User:createSynchroUser }
immobilier_manager_showUser:
    pattern: /show/user/{id}
    defaults: { _controller: ImmobilierManagerBundle:User:showUser }
######Gov list root###########
immobilier_manager_getGouvernorats:
    pattern:  /list/gouvernorats
    defaults: { _controller: ImmobilierManagerBundle:Default:getGouvernorats }
######Del list root###########
immobilier_manager_createDel:
    pattern:  /list/delegations
    defaults: { _controller: ImmobilierManagerBundle:Default:getDelegations }
######Loc list root###########
immobilier_manager_getLocations:
    pattern:  /list/locations
    defaults: { _controller: ImmobilierManagerBundle:Default:getLocations }
######Type list root###########
immobilier_manager_getTypes:
    pattern:  /list/types
    defaults: { _controller: ImmobilierManagerBundle:Default:getTypes }
######ANature list root###########
immobilier_manager_getNatures:
    pattern:  /list/natures
    defaults: { _controller: ImmobilierManagerBundle:Default:getNatures }
######Category list root###########
immobilier_manager_getCategories:
    pattern:  /list/category
    defaults: { _controller: ImmobilierManagerBundle:Default:getCategories }
######Annonce root###########
immobilier_manager_createAnnonce:
    pattern:  /create/annonce
    defaults: { _controller: ImmobilierManagerBundle:Default:createAnnonce }
######ShowAnnonce root###########
immobilier_manager_showAnnonce:
    pattern:  /show/annonce/{id}
    defaults: { _controller: ImmobilierManagerBundle:Default:showAnnonce }
######ListAnnonce root###########
immobilier_manager_listAnnonces:
    pattern:  /list/annonces
    defaults: { _controller: ImmobilierManagerBundle:Default:listAnnonces }