parameters:
#    immobilier_manager.example.class: Immobilier\ManagerBundle\Example

services:
#    immobilier_manager.example:
#        class: %immobilier_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
